import { Person } from "./base$Person";
import { PersonGroupExt } from "./base$PersonGroupExt";
import { Category } from "./sys$Category";
import { DicNonresidentType } from "./tsadv$DicNonresidentType";
import { DicMaritalStatus } from "./tsadv$DicMaritalStatus";
import { DicPersonType } from "./tsadv$DicPersonType";
import { DicNationality } from "./tsadv$DicNationality";
import { DicCitizenship } from "./tsadv$DicCitizenship";
export class PersonExt extends Person {
  static NAME = "base$PersonExt";
  children?: PersonGroupExt | null;
  category?: Category | null;
  nonresidentType?: DicNonresidentType | null;
  dateOfDeath?: any | null;
  group?: PersonGroupExt | null;
  maritalStatus?: DicMaritalStatus | null;
  type?: DicPersonType | null;
  nationality?: DicNationality | null;
  citizenship?: DicCitizenship | null;
  fullNameCyrillic?: string | null;
  fullNameNumberCyrillic?: string | null;
  fioWithEmployeeNumberWithSortSupported?: string | null;
}
export type PersonExtViewName =
  | "_minimal"
  | "_local"
  | "_base"
  | "person-view"
  | "person-edit"
  | "person-view_1"
  | "person.edit"
  | "personGroup.browse.person"
  | "person.info"
  | "person.candidate"
  | "person.full"
  | "person.minimal"
  | "person.browse"
  | "person-for-search"
  | "personExt.view.for.card"
  | "personExt.intern.edit"
  | "person.teamMember"
  | "personExt.for.intern.browse"
  | "person.uploadImage.recognition"
  | "assignment.card.person"
  | "personExt.for.recognition.image";
export type PersonExtView<V extends PersonExtViewName> = V extends "_minimal"
  ? Pick<
      PersonExt,
      "id" | "lastName" | "firstName" | "middleName" | "employeeNumber"
    >
  : V extends "_local"
  ? Pick<
      PersonExt,
      | "id"
      | "dateOfDeath"
      | "fullNameCyrillic"
      | "fullNameNumberCyrillic"
      | "fioWithEmployeeNumberWithSortSupported"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "firstName"
      | "firstNameLatin"
      | "middleNameLatin"
      | "lastName"
      | "lastNameLatin"
      | "middleName"
      | "hireDate"
      | "nationalIdentifier"
      | "dateOfBirth"
      | "employeeNumber"
      | "fullName"
      | "firstLastName"
      | "shortName"
      | "fioWithEmployeeNumber"
      | "fullNameLatin"
      | "fistLastNameLatin"
    >
  : V extends "_base"
  ? Pick<
      PersonExt,
      | "id"
      | "lastName"
      | "firstName"
      | "middleName"
      | "employeeNumber"
      | "dateOfDeath"
      | "fullNameCyrillic"
      | "fullNameNumberCyrillic"
      | "fioWithEmployeeNumberWithSortSupported"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "firstNameLatin"
      | "middleNameLatin"
      | "lastNameLatin"
      | "hireDate"
      | "nationalIdentifier"
      | "dateOfBirth"
      | "fullName"
      | "firstLastName"
      | "shortName"
      | "fioWithEmployeeNumber"
      | "fullNameLatin"
      | "fistLastNameLatin"
    >
  : V extends "person-view"
  ? Pick<
      PersonExt,
      | "id"
      | "firstName"
      | "lastName"
      | "middleName"
      | "maritalStatus"
      | "type"
      | "nationality"
      | "citizenship"
      | "employeeNumber"
      | "group"
      | "legacyId"
      | "image"
      | "nonresidentType"
    >
  : V extends "person-edit"
  ? Pick<
      PersonExt,
      | "id"
      | "version"
      | "createTs"
      | "createdBy"
      | "updateTs"
      | "updatedBy"
      | "deleteTs"
      | "deletedBy"
      | "lastName"
      | "firstName"
      | "middleName"
      | "employeeNumber"
      | "category"
      | "maritalStatus"
      | "type"
      | "nationality"
      | "citizenship"
      | "group"
      | "legacyId"
      | "nonresidentType"
      | "dateOfDeath"
      | "writeHistory"
      | "firstNameLatin"
      | "middleNameLatin"
      | "lastNameLatin"
      | "sex"
    >
  : V extends "person-view_1"
  ? Pick<
      PersonExt,
      | "id"
      | "dateOfDeath"
      | "fullNameCyrillic"
      | "fullNameNumberCyrillic"
      | "fioWithEmployeeNumberWithSortSupported"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "firstName"
      | "firstNameLatin"
      | "middleNameLatin"
      | "lastName"
      | "lastNameLatin"
      | "middleName"
      | "hireDate"
      | "nationalIdentifier"
      | "dateOfBirth"
      | "employeeNumber"
      | "fullName"
      | "firstLastName"
      | "shortName"
      | "fioWithEmployeeNumber"
      | "fullNameLatin"
      | "fistLastNameLatin"
      | "children"
      | "group"
      | "maritalStatus"
      | "type"
      | "nationality"
      | "citizenship"
      | "image"
    >
  : V extends "person.edit"
  ? Pick<
      PersonExt,
      | "id"
      | "firstName"
      | "lastName"
      | "middleName"
      | "employeeNumber"
      | "group"
      | "maritalStatus"
      | "type"
      | "nationality"
      | "citizenship"
      | "hireDate"
      | "image"
      | "nonresidentType"
    >
  : V extends "personGroup.browse.person"
  ? Pick<
      PersonExt,
      | "id"
      | "dateOfDeath"
      | "fullNameCyrillic"
      | "fullNameNumberCyrillic"
      | "fioWithEmployeeNumberWithSortSupported"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "firstName"
      | "firstNameLatin"
      | "middleNameLatin"
      | "lastName"
      | "lastNameLatin"
      | "middleName"
      | "hireDate"
      | "nationalIdentifier"
      | "dateOfBirth"
      | "employeeNumber"
      | "fullName"
      | "firstLastName"
      | "shortName"
      | "fioWithEmployeeNumber"
      | "fullNameLatin"
      | "fistLastNameLatin"
      | "sex"
      | "type"
      | "image"
    >
  : V extends "person.info"
  ? Pick<
      PersonExt,
      | "id"
      | "dateOfDeath"
      | "fullNameCyrillic"
      | "fullNameNumberCyrillic"
      | "fioWithEmployeeNumberWithSortSupported"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "firstName"
      | "firstNameLatin"
      | "middleNameLatin"
      | "lastName"
      | "lastNameLatin"
      | "middleName"
      | "hireDate"
      | "nationalIdentifier"
      | "dateOfBirth"
      | "employeeNumber"
      | "fullName"
      | "firstLastName"
      | "shortName"
      | "fioWithEmployeeNumber"
      | "fullNameLatin"
      | "fistLastNameLatin"
      | "maritalStatus"
      | "type"
      | "nationality"
      | "citizenship"
      | "sex"
      | "group"
      | "image"
    >
  : V extends "person.candidate"
  ? Pick<
      PersonExt,
      | "id"
      | "lastName"
      | "firstName"
      | "middleName"
      | "employeeNumber"
      | "group"
      | "maritalStatus"
      | "type"
      | "nationality"
      | "citizenship"
      | "nationalIdentifier"
      | "dateOfBirth"
      | "sex"
      | "fullName"
      | "shortName"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "image"
    >
  : V extends "person.full"
  ? Pick<
      PersonExt,
      | "id"
      | "version"
      | "createTs"
      | "createdBy"
      | "updateTs"
      | "updatedBy"
      | "deleteTs"
      | "deletedBy"
      | "dateOfDeath"
      | "fullNameCyrillic"
      | "fullNameNumberCyrillic"
      | "fioWithEmployeeNumberWithSortSupported"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "firstName"
      | "firstNameLatin"
      | "middleNameLatin"
      | "lastName"
      | "lastNameLatin"
      | "middleName"
      | "hireDate"
      | "nationalIdentifier"
      | "dateOfBirth"
      | "employeeNumber"
      | "fullName"
      | "firstLastName"
      | "shortName"
      | "fioWithEmployeeNumber"
      | "fullNameLatin"
      | "fistLastNameLatin"
      | "group"
      | "maritalStatus"
      | "type"
      | "nationality"
      | "citizenship"
      | "sex"
      | "image"
    >
  : V extends "person.minimal"
  ? Pick<
      PersonExt,
      | "id"
      | "firstName"
      | "lastName"
      | "middleName"
      | "image"
      | "type"
      | "legacyId"
      | "startDate"
      | "endDate"
      | "firstNameLatin"
      | "middleNameLatin"
      | "lastNameLatin"
      | "hireDate"
      | "employeeNumber"
    >
  : V extends "person.browse"
  ? Pick<
      PersonExt,
      | "id"
      | "legacyId"
      | "nationalIdentifier"
      | "dateOfBirth"
      | "sex"
      | "fioWithEmployeeNumber"
      | "hireDate"
      | "startDate"
      | "endDate"
      | "type"
      | "image"
      | "group"
      | "firstName"
      | "firstNameLatin"
      | "middleNameLatin"
      | "lastName"
      | "lastNameLatin"
      | "middleName"
      | "writeHistory"
      | "maritalStatus"
    >
  : V extends "person-for-search"
  ? Pick<
      PersonExt,
      | "id"
      | "startDate"
      | "endDate"
      | "group"
      | "firstNameLatin"
      | "lastNameLatin"
    >
  : V extends "personExt.view.for.card"
  ? Pick<
      PersonExt,
      | "id"
      | "dateOfDeath"
      | "fullNameCyrillic"
      | "fullNameNumberCyrillic"
      | "fioWithEmployeeNumberWithSortSupported"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "firstName"
      | "firstNameLatin"
      | "middleNameLatin"
      | "lastName"
      | "lastNameLatin"
      | "middleName"
      | "hireDate"
      | "nationalIdentifier"
      | "dateOfBirth"
      | "employeeNumber"
      | "fullName"
      | "firstLastName"
      | "shortName"
      | "fioWithEmployeeNumber"
      | "fullNameLatin"
      | "fistLastNameLatin"
      | "type"
    >
  : V extends "personExt.intern.edit"
  ? Pick<
      PersonExt,
      | "id"
      | "dateOfDeath"
      | "fullNameCyrillic"
      | "fullNameNumberCyrillic"
      | "fioWithEmployeeNumberWithSortSupported"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "firstName"
      | "firstNameLatin"
      | "middleNameLatin"
      | "lastName"
      | "lastNameLatin"
      | "middleName"
      | "hireDate"
      | "nationalIdentifier"
      | "dateOfBirth"
      | "employeeNumber"
      | "fullName"
      | "firstLastName"
      | "shortName"
      | "fioWithEmployeeNumber"
      | "fullNameLatin"
      | "fistLastNameLatin"
      | "group"
      | "maritalStatus"
      | "type"
      | "sex"
      | "nationality"
      | "citizenship"
    >
  : V extends "person.teamMember"
  ? Pick<
      PersonExt,
      | "id"
      | "dateOfDeath"
      | "fullNameCyrillic"
      | "fullNameNumberCyrillic"
      | "fioWithEmployeeNumberWithSortSupported"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "firstName"
      | "firstNameLatin"
      | "middleNameLatin"
      | "lastName"
      | "lastNameLatin"
      | "middleName"
      | "hireDate"
      | "nationalIdentifier"
      | "dateOfBirth"
      | "employeeNumber"
      | "fullName"
      | "firstLastName"
      | "shortName"
      | "fioWithEmployeeNumber"
      | "fullNameLatin"
      | "fistLastNameLatin"
      | "group"
      | "image"
    >
  : V extends "personExt.for.intern.browse"
  ? Pick<
      PersonExt,
      | "id"
      | "lastName"
      | "firstName"
      | "middleName"
      | "employeeNumber"
      | "group"
      | "startDate"
      | "endDate"
      | "nationalIdentifier"
    >
  : V extends "person.uploadImage.recognition"
  ? Pick<
      PersonExt,
      | "id"
      | "dateOfDeath"
      | "fullNameCyrillic"
      | "fullNameNumberCyrillic"
      | "fioWithEmployeeNumberWithSortSupported"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "firstName"
      | "firstNameLatin"
      | "middleNameLatin"
      | "lastName"
      | "lastNameLatin"
      | "middleName"
      | "hireDate"
      | "nationalIdentifier"
      | "dateOfBirth"
      | "employeeNumber"
      | "fullName"
      | "firstLastName"
      | "shortName"
      | "fioWithEmployeeNumber"
      | "fullNameLatin"
      | "fistLastNameLatin"
      | "type"
      | "image"
      | "group"
    >
  : V extends "assignment.card.person"
  ? Pick<
      PersonExt,
      | "id"
      | "dateOfDeath"
      | "fullNameCyrillic"
      | "fullNameNumberCyrillic"
      | "fioWithEmployeeNumberWithSortSupported"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "firstName"
      | "firstNameLatin"
      | "middleNameLatin"
      | "lastName"
      | "lastNameLatin"
      | "middleName"
      | "hireDate"
      | "nationalIdentifier"
      | "dateOfBirth"
      | "employeeNumber"
      | "fullName"
      | "firstLastName"
      | "shortName"
      | "fioWithEmployeeNumber"
      | "fullNameLatin"
      | "fistLastNameLatin"
      | "maritalStatus"
      | "type"
      | "nationality"
      | "citizenship"
      | "sex"
      | "group"
      | "image"
      | "nonresidentType"
    >
  : V extends "personExt.for.recognition.image"
  ? Pick<
      PersonExt,
      | "id"
      | "lastName"
      | "firstName"
      | "middleName"
      | "employeeNumber"
      | "legacyId"
      | "startDate"
      | "endDate"
      | "image"
      | "group"
    >
  : never;
