import { AbstractDictionary } from "./AbstractDictionary";
export class DicLearningCenter extends AbstractDictionary {
  static NAME = "tsadv$DicLearningCenter";
  address?: string | null;
  latitude?: any | null;
  longitude?: any | null;
}
export type DicLearningCenterViewName =
  | "_base"
  | "_local"
  | "_minimal"
  | "dicLearningCenter-browse"
  | "dicLearningCenter-edit";
export type DicLearningCenterView<
  V extends DicLearningCenterViewName
> = V extends "_base"
  ? Pick<
      DicLearningCenter,
      | "id"
      | "langValue"
      | "langValue1"
      | "langValue2"
      | "langValue3"
      | "langValue4"
      | "langValue5"
      | "address"
      | "latitude"
      | "longitude"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "description1"
      | "description2"
      | "description3"
      | "description4"
      | "description5"
      | "startDate"
      | "endDate"
      | "code"
      | "isSystemRecord"
      | "active"
      | "isDefault"
      | "order"
    >
  : V extends "_local"
  ? Pick<
      DicLearningCenter,
      | "id"
      | "address"
      | "latitude"
      | "longitude"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "langValue1"
      | "description1"
      | "langValue2"
      | "description2"
      | "langValue3"
      | "description3"
      | "langValue4"
      | "description4"
      | "langValue5"
      | "description5"
      | "startDate"
      | "endDate"
      | "code"
      | "isSystemRecord"
      | "active"
      | "isDefault"
      | "order"
    >
  : V extends "_minimal"
  ? Pick<
      DicLearningCenter,
      | "id"
      | "langValue"
      | "langValue1"
      | "langValue2"
      | "langValue3"
      | "langValue4"
      | "langValue5"
    >
  : V extends "dicLearningCenter-browse"
  ? Pick<
      DicLearningCenter,
      | "id"
      | "address"
      | "latitude"
      | "longitude"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "langValue1"
      | "description1"
      | "langValue2"
      | "description2"
      | "langValue3"
      | "description3"
      | "langValue4"
      | "description4"
      | "langValue5"
      | "description5"
      | "startDate"
      | "endDate"
      | "code"
      | "isSystemRecord"
      | "active"
      | "isDefault"
      | "order"
      | "company"
    >
  : V extends "dicLearningCenter-edit"
  ? Pick<
      DicLearningCenter,
      | "id"
      | "address"
      | "latitude"
      | "longitude"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "langValue1"
      | "description1"
      | "langValue2"
      | "description2"
      | "langValue3"
      | "description3"
      | "langValue4"
      | "description4"
      | "langValue5"
      | "description5"
      | "startDate"
      | "endDate"
      | "code"
      | "isSystemRecord"
      | "active"
      | "isDefault"
      | "order"
      | "company"
    >
  : never;
