import {UserExt} from "./base$UserExt";
import {PersonGroupExt} from "./base$PersonGroupExt";

export class TsadvUserExt extends UserExt {
  static NAME = "tsadv$UserExt";
  personGroup?: PersonGroupExt | null;
}

export type UserExtViewName =
  | "_base"
  | "_local"
  | "_minimal"
  | "tsadvUserExt-view"
  | "user.browse"
  | "user.edit"
  | "user.roles"
  | "userExt.edit";
export type UserExtView<V extends UserExtViewName> = V extends "_base"
  ? Pick<TsadvUserExt,
    | "id"
    | "shortName"
    | "login"
    | "loginLowerCase"
    | "password"
    | "passwordEncryption"
    | "name"
    | "firstName"
    | "lastName"
    | "middleName"
    | "position"
    | "email"
    | "language"
    | "timeZone"
    | "timeZoneAuto"
    | "active"
    | "changePasswordAtNextLogon"
    | "groupNames"
    | "ipMask"
    | "sysTenantId"
    | "atsCode"
    | "innerNumber"
    | "availability"
    | "mobilePhone"
    | "telegramCode"
    | "telegramChatId"
    | "passwordChangeDate"
    | "fullName">
  : V extends "_local"
    ? Pick<UserExt,
      | "id"
      | "login"
      | "loginLowerCase"
      | "password"
      | "passwordEncryption"
      | "name"
      | "firstName"
      | "lastName"
      | "middleName"
      | "position"
      | "email"
      | "language"
      | "timeZone"
      | "timeZoneAuto"
      | "active"
      | "changePasswordAtNextLogon"
      | "groupNames"
      | "ipMask"
      | "sysTenantId"
      | "atsCode"
      | "innerNumber"
      | "availability"
      | "mobilePhone"
      | "telegramCode"
      | "telegramChatId"
      | "passwordChangeDate"
      | "shortName"
      | "fullName">
    : V extends "_minimal"
      ? Pick<TsadvUserExt, "id" | "shortName">
      : V extends "tsadvUserExt-view"
        ? Pick<TsadvUserExt,
          | "id"
          | "login"
          | "loginLowerCase"
          | "password"
          | "passwordEncryption"
          | "name"
          | "firstName"
          | "lastName"
          | "middleName"
          | "position"
          | "email"
          | "language"
          | "timeZone"
          | "timeZoneAuto"
          | "active"
          | "changePasswordAtNextLogon"
          | "groupNames"
          | "ipMask"
          | "sysTenantId"
          | "group"
          | "userRoles"
          | "substitutions"
          | "image"
          | "addressBookEntries"
          | "availability"
          | "innerNumber"
          | "atsCode"
          | "image"
          | "addressBookEntries"
          | "availability"
          | "innerNumber"
          | "atsCode"
          | "personGroup"
          | "personGroup">
        : V extends "user.browse"
          ? Pick<TsadvUserExt,
            | "id"
            | "version"
            | "createTs"
            | "createdBy"
            | "updateTs"
            | "updatedBy"
            | "deleteTs"
            | "deletedBy"
            | "login"
            | "loginLowerCase"
            | "password"
            | "passwordEncryption"
            | "name"
            | "firstName"
            | "lastName"
            | "middleName"
            | "position"
            | "email"
            | "language"
            | "timeZone"
            | "timeZoneAuto"
            | "active"
            | "changePasswordAtNextLogon"
            | "groupNames"
            | "ipMask"
            | "sysTenantId"
            | "group"
            | "image"
            | "image">
          : V extends "user.edit"
            ? Pick<TsadvUserExt,
              | "id"
              | "login"
              | "loginLowerCase"
              | "password"
              | "passwordEncryption"
              | "name"
              | "firstName"
              | "lastName"
              | "middleName"
              | "position"
              | "email"
              | "language"
              | "timeZone"
              | "timeZoneAuto"
              | "active"
              | "changePasswordAtNextLogon"
              | "groupNames"
              | "ipMask"
              | "sysTenantId"
              | "group"
              | "userRoles"
              | "substitutions"
              | "image"
              | "addressBookEntries"
              | "availability"
              | "innerNumber"
              | "atsCode"
              | "image"
              | "addressBookEntries"
              | "availability"
              | "innerNumber"
              | "atsCode"
              | "personGroup">
            : V extends "user.roles"
              ? Pick<TsadvUserExt, "id" | "shortName" | "userRoles">
              : V extends "userExt.edit"
                ? Pick<TsadvUserExt,
                  | "id"
                  | "shortName"
                  | "image"
                  | "fullName"
                  | "firstName"
                  | "lastName"
                  | "middleName"
                  | "mobilePhone"
                  | "telegramChatId"
                  | "email"
                  | "language"
                  | "personGroup">
                : never;
