import { BaseUuidEntity } from "./sys$BaseUuidEntity";
import { WorkedHoursSummary } from "./tsadv$WorkedHoursSummary";
import { TimecardHeader } from "./tsadv$TimecardHeader";
export class Timecard extends BaseUuidEntity {
  static NAME = "tsadv$Timecard";
  name?: string | null;
  costCenterString?: string | null;
  workedHoursSummaries?: WorkedHoursSummary | null;
  assignmentGroupId?: any | null;
  assignmentGroupLegacyId?: string | null;
  timecardHeaders?: TimecardHeader | null;
  positionName?: string | null;
  schedules?: string | null;
  corrective?: boolean | null;
  summary1?: WorkedHoursSummary | null;
  summary2?: WorkedHoursSummary | null;
  summary3?: WorkedHoursSummary | null;
  summary4?: WorkedHoursSummary | null;
  summary5?: WorkedHoursSummary | null;
  summary6?: WorkedHoursSummary | null;
  summary7?: WorkedHoursSummary | null;
  summary8?: WorkedHoursSummary | null;
  summary9?: WorkedHoursSummary | null;
  summary10?: WorkedHoursSummary | null;
  summary11?: WorkedHoursSummary | null;
  summary12?: WorkedHoursSummary | null;
  summary13?: WorkedHoursSummary | null;
  summary14?: WorkedHoursSummary | null;
  summary15?: WorkedHoursSummary | null;
  summary16?: WorkedHoursSummary | null;
  summary17?: WorkedHoursSummary | null;
  summary18?: WorkedHoursSummary | null;
  summary19?: WorkedHoursSummary | null;
  summary20?: WorkedHoursSummary | null;
  summary21?: WorkedHoursSummary | null;
  summary22?: WorkedHoursSummary | null;
  summary23?: WorkedHoursSummary | null;
  summary24?: WorkedHoursSummary | null;
  summary25?: WorkedHoursSummary | null;
  summary26?: WorkedHoursSummary | null;
  summary27?: WorkedHoursSummary | null;
  summary28?: WorkedHoursSummary | null;
  summary29?: WorkedHoursSummary | null;
  summary30?: WorkedHoursSummary | null;
  summary31?: WorkedHoursSummary | null;
  baseWorkHours?: any | null;
  planWorkDays?: number | null;
  planWorkHours?: any | null;
  baseWorkDays?: number | null;
  factHoursWithoutOvertime?: any | null;
  overtimeHours?: any | null;
  factWorkDays?: number | null;
  dayHours?: any | null;
  nightHours?: any | null;
  annualVacationDays?: number | null;
  unpaidVacationDays?: number | null;
  sickDays?: number | null;
  absenceDays?: number | null;
  totalFreeDays?: number | null;
  bussinessTrip?: number | null;
  totalAbsence?: number | null;
  totalWorkedDays?: number | null;
  grandTotalDays?: number | null;
  downtime?: number | null;
  quarantine?: number | null;
}
export type TimecardViewName = "_minimal" | "_local" | "_base";
export type TimecardView<V extends TimecardViewName> = never;
