import { AbstractDictionary } from "./AbstractDictionary";
export class DicRequisitionAccessLevel extends AbstractDictionary {
  static NAME = "tsadv$DicRequisitionAccessLevel";
}
export type DicRequisitionAccessLevelViewName =
  | "_base"
  | "_local"
  | "_minimal"
  | "dicRequisitionAccessLevel-browse"
  | "dicRequisitionAccessLevel-edit";
export type DicRequisitionAccessLevelView<
  V extends DicRequisitionAccessLevelViewName
> = V extends "_base"
  ? Pick<
      DicRequisitionAccessLevel,
      | "id"
      | "langValue"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "langValue1"
      | "description1"
      | "langValue2"
      | "description2"
      | "langValue3"
      | "description3"
      | "langValue4"
      | "description4"
      | "langValue5"
      | "description5"
      | "startDate"
      | "endDate"
      | "code"
      | "isSystemRecord"
      | "active"
      | "isDefault"
      | "order"
    >
  : V extends "_local"
  ? Pick<
      DicRequisitionAccessLevel,
      | "id"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "langValue1"
      | "description1"
      | "langValue2"
      | "description2"
      | "langValue3"
      | "description3"
      | "langValue4"
      | "description4"
      | "langValue5"
      | "description5"
      | "startDate"
      | "endDate"
      | "code"
      | "isSystemRecord"
      | "active"
      | "isDefault"
      | "order"
    >
  : V extends "_minimal"
  ? Pick<DicRequisitionAccessLevel, "id" | "langValue">
  : V extends "dicRequisitionAccessLevel-browse"
  ? Pick<
      DicRequisitionAccessLevel,
      | "id"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "langValue1"
      | "description1"
      | "langValue2"
      | "description2"
      | "langValue3"
      | "description3"
      | "langValue4"
      | "description4"
      | "langValue5"
      | "description5"
      | "startDate"
      | "endDate"
      | "code"
      | "isSystemRecord"
      | "active"
      | "isDefault"
      | "order"
      | "company"
    >
  : V extends "dicRequisitionAccessLevel-edit"
  ? Pick<
      DicRequisitionAccessLevel,
      | "id"
      | "legacyId"
      | "organizationBin"
      | "integrationUserLogin"
      | "langValue1"
      | "description1"
      | "langValue2"
      | "description2"
      | "langValue3"
      | "description3"
      | "langValue4"
      | "description4"
      | "langValue5"
      | "description5"
      | "startDate"
      | "endDate"
      | "code"
      | "isSystemRecord"
      | "active"
      | "isDefault"
      | "order"
      | "company"
    >
  : never;
