-- begin KZM_CONCOURSE
alter table KZM_CONCOURSE add constraint FK_KZM_CONCOURSE_ON_BANNER foreign key (BANNER_ID) references SYS_FILE(ID)^
alter table KZM_CONCOURSE add constraint FK_KZM_CONCOURSE_ON_REQUEST_TEMPLATE foreign key (REQUEST_TEMPLATE_ID) references SYS_FILE(ID)^
create index IDX_KZM_CONCOURSE_ON_BANNER on KZM_CONCOURSE (BANNER_ID)^
create index IDX_KZM_CONCOURSE_ON_REQUEST_TEMPLATE on KZM_CONCOURSE (REQUEST_TEMPLATE_ID)^
-- end KZM_CONCOURSE
