alter table KZM_POSITION_OVERLAPPING_REQUEST rename column file_id to file_id__u14567 ;
alter table KZM_POSITION_OVERLAPPING_REQUEST drop constraint FK_KZM_POSITION_OVERLAPPING_REQUEST_ON_FILE ;
drop index IDX_KZM_POSITION_OVERLAPPING_REQUEST_ON_FILE ;
alter table KZM_POSITION_OVERLAPPING_REQUEST add column JUSTIFICATION varchar(2500) ;
alter table KZM_POSITION_OVERLAPPING_REQUEST add column WORK_COMPLETION_DATE date ;
alter table KZM_POSITION_OVERLAPPING_REQUEST add column ATTACHMENT_ID uuid ;
-- alter table KZM_POSITION_OVERLAPPING_REQUEST add column POSITION_ID uuid ^
-- update KZM_POSITION_OVERLAPPING_REQUEST set POSITION_ID = <default_value> ;
-- alter table KZM_POSITION_OVERLAPPING_REQUEST alter column POSITION_ID set not null ;
alter table KZM_POSITION_OVERLAPPING_REQUEST add column POSITION_ID uuid not null ;
